google_analytics: ## Your google analytics token here. Can be empty. See https://analytics.google.com/

# ------------------------------------------
# Content Settings
# ------------------------------------------
timezone: Asia/Tokyo ## Should be TZ identifier. See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

## The settings of the navy bar. Layout settings: see `toc` below
navbar:
  enable: true ## Warning: if this is false, the multi-language function will be disabled.
  links: 
    - url: '/Multilingual_Academic_Page_Template' ## Defined in the `permalink`
      label: 'Template Home'
      target: ''
    - url: 'https://www.google.com/'
      label: 'Outside Page'
      target: '_blank'
    - url: 'https://www.hakaze-c.com/'
      label: "Author's Page"
      target: '_blank'

footnotes: | 
  Your footnotes here.

## Publication List Settings
publication_list:
  - file: 'example_list_1' ## Should be saved in the `data` path.
    title: 
      ## If the language is not presented in the title dictionary, the list will not be presented in such language.
      en: 'International Conference'
      jp: '国際会議'
      zh: '国际会议'
    style: 'international_conf' ## Should be defined and indexed in the _includes/publication_list_style. Basically the `international_conf` is good for all scenarios.
    calculate_statics: True
  - file: 'example_list_2'
    title: 
      en: 'Pre-print'
      jp: 'プレプリント'
      zh: '预印本'
    style: 'preprint'
    calculate_statics: True

name_to_bold: # Which author names should be in bold?
  - 'Saved Author 1'
  - 'Saved Author 2'

publication_statics: # Init-* = e.g. statics of the Thesis
  init_pages: 0
  init_if: 0
  init_count: 0
  translations:
    en:
      total_publications: 'Total Publications: '
      cif: 'Cumulative Impact Factor: '
      pages: 'Total Pages: '
    jp:
      total_publications: '発表数: '
      cif: '累積IF: '
      pages: '総ページ数: '
    zh:
      total_publications: '论文数: '
      cif: '累计影响因子: '
      pages: '总页数: '

# ------------------------------------------
# Layout Settings
# ------------------------------------------
## Main Fonts
fonts: ## Directly use CSS format as string here.
  default: | ## If the language is not declared?
      'Noto Sans JP', "Noto Sans SC", Tahoma, arial, helvetica, Sans-Serif
  normal: 
    en: | 
      'Noto Sans JP', 'Gentium Basic' 
    jp: |
      'Noto Sans JP', Tahoma, arial, helvetica
    zh: |
      'Noto Sans SC'
  title: "'Gentium Basic', 'Noto Serif JP', 'Noto Serif SC'"
  includes: | ## To make sure your font is included in the site. Refer to https://fonts.google.com/. 
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Gentium+Basic" />
    <link href="https://fonts.googleapis.com/css2?family=Gentium+Plus:ital,wght@0,400;0,700;1,400;1,700&family=Noto+Sans+SC:wght@100..900&family=Noto+Serif+JP:wght@200..900&family=Noto+Serif+SC:wght@200..900&display=swap" rel="stylesheet">

## Markdown Settings
font_scale: 100%
font_colors:
  normal: "#000000" ## The color of normal texts
  link_normal: "#2a66cc"
  link_clicked: "#070a7d"
  title_underline_color: "#000000"
  end_mark_color: "#000000"

## Background (i.e., the area lower than the "paper-looked" part) Settings
background:
  color: "#e9f0ff"
  pattern: "radial-gradient(circle at 20px 20px, #ffffff 5px, transparent 0)"
  pattern_size: "40pt 40pt"
  image: ## Empty to use the pure color + pattern

## Writing Area (i.e., the area with markdown texts)
writing_area:
  background_color: "rgba(255, 255, 255, 0.95)"
  margin: 18 ## percent  Notice this margin will also move the toc and the top and bottom bar.
  padding: "2% 3% 1.5% 3%" ## the blank area in the boundary of the writing area. up, left, down, right

## Table of Content Settings
## NOTICE: THE background_color, fonts, boarder settings is reused by the navybar.
toc:
  enabled: true
  levels: "h1, h2" ## Which titles is contained in the TOC? e.g., "h1, h2" or "h2, h3, h4"
  locationX: left ## `left` or `right`
  locationY: 50% ## The length from the bottom of the page to the Center of the toc
  background_color: rgba(255, 255, 255, 0.5) ## The background color of the toc
  boarder: "2pt solid #ffffff" ## The boarder settings of the toc. Line width, line style, line color.
  fonts: | ## Should be included in the aforementioned fonts.includes
    'Noto Sans JP', "Noto Sans SC"
  fontsize: 14px

## Details Panel (the paper abstracts and bibtex)
details_panel:
  background_color: "#eff4ff"
  border: "2px solid #b0c8ff"

# ------------------------------------------
# Advanced
# ------------------------------------------

more_heads: |
  <style>
    .katex-display>.katex {
      white-space: normal;
    }
  </style>
more_footers: 

# ------------------------------------------
# The following should be kept unmodified.
# ------------------------------------------

data_dir: data

markdown: kramdown
kramdown:
  input: GFM

sass:
  sass_dir: css
  style: compressed

theme: jekyll-theme-primer